#!/bin/bash

set -uexo

CONTAINER_MEM="${CONTAINER_MEM:-1G}"
HOST_PI_CONFIG_DIR=${HOST_PI_CONFIG_DIR:-~/.pi}
HOST_WORK_DIR="${HOST_WORK_DIR:-$PWD}"
IMAGE_TAG=${IMAGE_TAG:-pineapple}

container run \
  --memory $CONTAINER_MEM \
  --interactive \
  --tty \
  --volume "$HOST_PI_CONFIG_DIR:/home/pineapple/.pi" \
  --volume "$HOST_WORK_DIR:/workspace" \
  $IMAGE_TAG \
  "$@"

