#!/usr/bin/env python3

import argparse
import os


def build_container(file, tag):
  os.system(f'container build --file {file} --tag {tag}')


if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser._action_groups.pop()
  required = parser.add_argument_group('required arguments')
  required.add_argument('-f', '--file', required=True, help='name of container file')
  required.add_argument('-t', '--tag', required=True, help='tag for created image')
  args = parser.parse_args()
  build_container(args.file, args.tag)
