# 2026-07-26 Adapted from https://github.com/jbreer/claude-code-in-apple-container/

FROM node:26-trixie-slim

# Etc/UTC is the canonical format.  Really.
ARG TZ="Etc/UTC"
ARG USERNAME=pineapple

ENV TZ="$TZ" \
  LANG=en_US.UTF-8 \
  LC_ALL=en_US.UTF-8 \
  EDITOR=nvim \
  VISUAL=nvim \
  DEVCONTAINER=true \
  PATH=/home/${USERNAME}/.local/bin:${PATH}

RUN << EOF
  apt-get -qq update 
  apt-get -qq -y --no-install-recommends install \
    ca-certificates \
    git \
    iproute2 \
    locales \
    neovim \
    ripgrep
  apt-get -qq clean
  rm -rf /var/lib/apt/lists/*
  sed -i '/en_US.UTF-8/s/^# //' /etc/locale.gen 
  locale-gen
EOF

# node:26 ships with a 'node' user/group at UID/GID 1000
# remove user and group and create pineapple with same id's
ARG PI_UID=1000
ARG PI_GID=1000
RUN << EOF 
  userdel --remove node 2>/dev/null
  groupdel node 2>/dev/null
  groupadd --gid ${PI_GID} ${USERNAME}
  useradd --uid ${PI_UID} --gid ${PI_GID} --create-home --shell /bin/bash ${USERNAME}
  mkdir /command-history
  touch /command-history/.bash_history
  chown -R ${USERNAME} /command-history
  mkdir -p /workspace /home/${USERNAME}/.pi 
  chown -R ${USERNAME}:${USERNAME} /workspace /home/${USERNAME}/.pi
EOF

RUN npm install -g --ignore-scripts @earendil-works/pi-coding-agent

USER ${USERNAME}
WORKDIR /workspace

# ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["/usr/local/bin/pi"]

